general {
  after_sleep_cmd=hyprctl dispatch dpms on
  before_sleep_cmd=loginctl lock-session
  lock_cmd=playerctl --all-players pause && pidof hyprlock || hyprlock
}

listener {
  on-resume=brightnessctl -r
  on-timeout=brightnessctl -s set 10
  timeout=480
}

listener {
  on-timeout=loginctl lock-session
  timeout=600
}

listener {
  on-resume=hyprctl dispatch dpms on && brightnessctl -r
  on-timeout=hyprctl dispatch dpms off
  timeout=660
}

listener {
  on-timeout=systemctl suspend
  timeout=1800
}
