authentication {
  pam {
    enable=true
  }
}

background {
  monitor=
  blur_passes=3
  blur_size=3
  brightness=0.500000
  contrast=1.000000
  path=$HOME/Pictures/lockscreen/lockscreen.jpg
  vibrancy=0.000000
  vibrancy_darkness=0.000000
}

general {
  hide_cursor=true
  ignore_empty_input=true
  no_fade_in=false
}

input-field {
  size=200, 50
  bothlock_color=-1
  capslock_color=-1
  check_color=#a1efe4
  dots_center=true
  dots_rounding=-1
  dots_size=0.330000
  dots_spacing=0.150000
  fade_on_empty=true
  fade_timeout=1000
  fail_color=#f92672
  fail_text=<i>$FAIL <b>($ATTEMPTS)</b></i>
  fail_transition=300
  font_color=#383830
  halign=center
  hide_input=false
  inner_color=#66d9ef
  invert_numlock=false
  numlock_color=-1
  outer_color=#f9f8f5
  outline_thickness=3
  placeholder_text=<i>Input Password...</i>
  position=0, -20
  rounding=40
  shadow_passes=10
  shadow_size=20
  swap_font_color=false
  valign=center
}

label {
  color=#f9f8f5
  font_size=20
  halign=right
  position=-100, 160
  shadow_passes=5
  shadow_size=10
  text=$USER
  valign=bottom
}

label {
  color=#f9f8f5
  font_size=55
  halign=right
  position=-100, 70
  shadow_passes=5
  shadow_size=10
  text=cmd[update:1000] echo $TIME
  valign=bottom
}
