# # -----------------------------------------------------
# # Window rules
# # -----------------------------------------------------
## Update rule: https://github.com/hyprwm/Hyprland/issues/9723

windowrule = tile,class:^(Microsoft-edge)$
windowrule = tile,class:^(Brave-browser)$
windowrule = tile,class:^(Chromium)$
windowrule = float,class:^(pavucontrol)$
windowrule = float,class:^(blueman-manager)$
windowrule = float,class:^(nm-connection-editor)$
windowrule = float,class:^(qalculate-gtk)$
windowrule = float,initialTitle:^(Hyprshot)$
windowrule = size 400 300,initialTitle:^(Hyprshot)$
windowrule = move 50% 50%,initialTitle:^(Hyprshot)$

# # Browser Picture in Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$
